import { describe, expect, it } from "vitest";

import truth from "./iso-weeks.fixture.json";
import { bucketPeriod, periodGrain, periodStartIso } from "./parse-values";

/**
 * Ground truth generated by Python's `date.isocalendar()` over three years
 * spanning two 53-week years and both year boundaries, where ISO weeks are
 * easiest to get wrong: 2023-12-31 belongs to 2023-W52 but 2024-12-30 belongs
 * to 2025-W01.
 */
describe("ISO week buckets", () => {
  const rows = truth as [string, string, string][];

  it("agrees with the calendar on every day for three years", () => {
    const wrong: string[] = [];
    for (const [day, week, monday] of rows) {
      const iso = `${day}T00:00:00.000Z`;
      const bucket = bucketPeriod(iso, "week");
      if (bucket !== week) wrong.push(`${day}: bucket ${bucket} != ${week}`);
      const start = periodStartIso(bucket).slice(0, 10);
      if (start !== monday) wrong.push(`${day}: start ${start} != ${monday}`);
    }
    expect(wrong).toEqual([]);
  });

  it("round-trips every week bucket back to its own grain", () => {
    const buckets = [...new Set(rows.map(([, week]) => week))];
    expect(buckets.length).toBeGreaterThan(150);
    expect(buckets.every((bucket) => periodGrain(bucket) === "week")).toBe(
      true,
    );
  });

  it("reads a day bucket as a day", () => {
    expect(bucketPeriod("2026-03-15T00:00:00.000Z", "day")).toBe("2026-03-15");
    expect(periodGrain("2026-03-15")).toBe("day");
    expect(periodStartIso("2026-03-15")).toBe("2026-03-15T00:00:00.000Z");
  });
});
